defaults:
  - base_gemma
  - _self_

name: gemma-7b
model: google/gemma-7b
dtype: bfloat16
layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]
instruct: False

selected_layers:
  sawmil:
    cities_loc: 15
    med_indications: 16
    defs: 16
  svm:
    cities_loc: 15
    med_indications: 15
    defs: 15
  mean_difference:
    cities_loc: 25
    med_indications: 20
    defs: 12